### PR TITLE
Configurable max message size.

### PR DESCRIPTION
**Pull request by RubenNL**
# Proposed Changes

* Made the message max size configurable.

## Related Issues

None

### CODE REVIEW

**Review by erik73 — CHANGES_REQUESTED** [review]
I think we should set an initial value of 10240000 (postfix default) for "message_size_limit", 
since this add-on is sometimes used on systems with limited storage space available.

Can you also update the DOCS.md to document the new configuration parameter?

**Review by erik73 — APPROVED** [review]
Look perfect to me!

**Comment by erik73** [comment]
@RubenNL 
This is not working. I got the following error on startup:

jq: error: syntax error, unexpected == (Unix shell quoting issues?) at <top-level>, line 1:
if (.message_size_limit, == null) then                         
jq: error: syntax error, unexpected '|' (Unix shell quoting issues?) at <top-level>, line 3:
        elif (.message_size_limit, | type == "string") then                                   
jq: error: syntax error, unexpected // (Unix shell quoting issues?) at <top-level>, line 4:
            .message_size_limit, // empty                                 
jq: error: Possibly unterminated 'if' statement at <top-level>, line 1:
if (.message_size_limit, == null) then
jq: 4 compile errors
bc: bad token at '* 1024000'
cont-init: info: /etc/cont-init.d/10-create-config.sh exited 1

**Comment by RubenNL** [comment]
I didn't test my last commit, which seems like is the problem. I can't test
it now, but I think I shouldn't have added the ',' on line 23 of the init
file.

Sorry for the inconvenience, I will make sure to test all future changes
more.

**Comment by erik73** [comment]
No problem. I removed the ','.
I will test it soon and report back.

**Comment by erik73** [comment]
@RubenNL .
I implemented the changes you suggested on line 23, and now it works as expected. I have released a new version.
Thanks for your help!

**Pull request merged**
